import mongoose from 'mongoose';

const eventSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    eventName: {
      type: String,
      trim: true,
    },
    description: {
      type: String,
      required: true,
    },
    location: {
      type: String,
      trim: true,
    },
    venue: {
      type: String,
      trim: true,
    },
    address: {
      type: String,
      trim: true,
    },
    date: {
      type: Date,
      required: true,
      index: true,
    },
    fromDate: {
      type: Date,
    },
    toDate: {
      type: Date,
    },
    time: {
      type: String,
      trim: true,
    },
    fromTime: {
      type: String,
      trim: true,
    },
    toTime: {
      type: String,
      trim: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    createdBySerNo: {
      type: Number,
      index: true,
    },
    createdByName: {
      type: String,
      trim: true,
    },
    eventType: {
      type: String,
      trim: true,
    },
    priority: {
      type: String,
      enum: ['High', 'Medium', 'Low'],
      default: 'Medium',
    },
    eventImage: {
      type: String,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    visibleToAllVansh: {
      type: Boolean,
      default: true,
    },
    visibleVanshNumbers: [
      {
        type: String,
        trim: true,
      },
    ],
  },
  { timestamps: true }
);

export default mongoose.model('Event', eventSchema, 'events');